### ISSUE TITLE
Exception thrown by the target

### ISSUE THREAD

**Issue by apperrault** [EvotecIT/PasswordSolution#13]
Hi there,
I am trying to run this against my production environment, as a domain admin, from an admin system in that environment, and every time I am getting the error below.  Any thoughts as to why this is happening?  I can provide additional logs if needed

[i] Getting replication data from domain.org using dc04.org
[e] Unable to get replication data from domain.org using dc04.org. Error: Exception has been thrown by the target of an invocation.
[i] Testing password quality

thanks
aaron

**Comment by PrzemyslawKlys** [comment]
Hi,

My suggestion is try to find the reason using direct command:

```powershell
Get-ADReplAccount -All -Server "dc04.org" 
```

Try  playing with one server, try other server, see if there's a difference. 

If it gives you error check what $error[0] variable holds, what is in ErrorDetails, Exception, and so on.

**Comment by apperrault** [comment]
hmmm, now I am getting this
PS C:\Scripts> Get-ADReplAccount -all -Server dc04pwm1.prod.us.oclc.org
At line:1 char:1
+ Get-ADReplAccount -all -Server dc04pwm1.prod.us.oclc.org
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
This script contains malicious content and has been blocked by your antivirus software.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ScriptContainedMaliciousContent

Windows defender is turned off and my AV product, CrowdStrike is not seeing this as being blocked

**Comment by PrzemyslawKlys** [comment]
Please "hide" your domain. If it's being reported as malicious you need to find the cause. I can't help with that.

**Comment by apperrault** [comment]
Oops. Meant to hide that. I will edit and remove it

**Comment by PrzemyslawKlys** [comment]
I already did it for you, and deleted history.
