### ISSUE TITLE
Support for "WeakPasswordHashes" parameter

### ISSUE THREAD

**Issue by PhiZ-9** [EvotecIT/PasswordSolution#14]
Hi there,

the DSInternals function `Test-PasswordQuality` supports two additional ways of supplying weak passwords in the form of NT(LM) hashes directly with `-WeakPasswordHashesFile` and `-WeakPasswordHashesSortedFile` [[1](https://github.com/MichaelGrafnetter/DSInternals/blob/master/Documentation/PowerShell/Test-PasswordQuality.md)]. This is a nice way to check for weak passwords using publicly available lists of hashes such as HaveIBeenPwned.

Would it be possible for you to add these parameters to `Find-PasswordQuality` (and to `Show-PasswordQuality`) so that we can directly specifiy hashes?

Many thanks in advance!

**Comment by CamFlyerCH** [comment]
I am missing the exactly same feature too !
