### ISSUE TITLE
Missing report sections in HTML

### ISSUE THREAD

**Issue by Radanca** [EvotecIT/PasswordSolution#16]
![HTML report](https://github.com/EvotecIT/PasswordSolution/assets/74746419/a447a574-791c-430f-87f4-8bd718155bf5)
Hello,
I ran show-passwordsolution in a recovery lab which is a copy of our production.
Everything works fine, I can read the HTML report file on any machine in the lab with Edge, Chrome and Firefox. When I copy the HTML file to machines in our production infrastructure, there is only the first section that is displayed, the other sections are empty, see the screenshot.
It seems to be the dynamic content that is not displaying.
Would the HTML file contain code that would be blocked by our monitoring tools such as an EDR?
Does reading the HTML file require any prerequisites to be read without difficulty?
Congratulations on the module, it does a superb job.

**Comment by PrzemyslawKlys** [comment]
Only you can tell - does the size changed before and after copying to production? If not, it's probably not that. 

You can also open F12 in the browser and see if it throws errors? 

Are you by any chance using `-Online` switch when generating reports? The online switch makes the file smaller by linking CSS/JS to CDN resources. If you have no internet on prod, or it's limited this could be reason why you see no data. My guess this is why...

**Comment by Radanca** [comment]
I restarted the server the report was running on, and now I see all sections of the report. maybe a loading problem with the PS module.
Thank you for your answer.
