### ISSUE TITLE
Formatting the date and adding a time zone to the password expiration date variable

### ISSUE THREAD

**Issue by KrzysztofRaczkiewicz** [EvotecIT/PasswordSolution#6]
TemplatePreExpirySubject           = '[Password Expiring] Your password will expire on $DateExpiry UTC ($DaysToExpire days)'

**Comment by PrzemyslawKlys** [comment]
It's now available:

![image](https://github.com/EvotecIT/PasswordSolution/assets/15063294/32e2bd8f-79a3-4fb9-ade5-0d4cbe715aad)

It applies to DateExpiry and PasswordLastSet only.
